version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000"
      - "9901:9901"
    depends_on:
      - crossword-game
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
  crossword-game:
    image: mcoot/crossword-game:latest
    command: ["./crossword-game"]