input_path: ./templates
output_path: ./out
backend:
  image: mcoot/crossword-game
  tag: latest
  container_name: crossword-game
  port: 8080
  healthcheck_path: /api/v1/health
envoy:
  image: envoyproxy/envoy
  tag: v1.33-latest
  port: 443
  admin_port: 9901
  tls:
    enabled: true
    cert_domain: donkdonk.spearritt.dev
    cert_email: me@spearritt.dev